### ISSUE TITLE
Potential logic error in `assertVarsSet`

### ISSUE THREAD

**Issue by amusingaxl** [makerdao/token-tests#3]
I'm reviewing the test suites here, and I'm a bit confused about this:

https://github.com/makerdao/token-tests/blob/e87772a56b28c806b482c89c03ac02b37de2c428/src/TokenTests.sol#L32-L37

The way it's implemented, it means that:

> If `_tokenName_` and `_symbol_` are defined, they are overwritten by the values read from the token contract.

Shouldn't it be the opposite?

Also, the name of the method is misleading: `assertVarsSet` should contain only assertions, not "global" assignments.

**Comment by telome** [comment]
Great catch! It's been fixed in 79d9e12.
